### ISSUE TITLE
policy=“translation” is failed

### ISSUE THREAD

**Issue by Johnson-yue** [mit-han-lab/data-efficient-gans#3]
Hi， I test you code with two framework, and two dataformat, and the same result is "translation" policy is failed!

Envs:
Python: 3.7
Ubuntu: 1804
CUDA 10.1
Pytorch: 1.4.0

#### Test1:
I use your code in [BMSG-GAN repo](https://github.com/akanimax/BMSG-GAN) and train 3-channel dataset(102 -flower) but only using 755 samples for checking, when the policy included "**translation**" , and failed to train. 

> RuntimeError: CuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input

but if policy I just used "**_color,cut_**", it work fine!

##### Test2:

In my own GAN  with 1-channel dataset, the performance is the same, if not use "**translation**" policy it work fine, otherwise it failed

**Comment by Johnson-yue** [comment]
When I use Python: 3.5 this bug is disappeared!!!

**Comment by zsyzzsoft** [comment]
I'm trying to fix it, but I cannot replicate the error. Could you help me to verify whether the updated code works now on Python 3.7? Thank you!

**Comment by junyanz** [comment]
maybe we should mention PyTorch/Tensorflow version in the README.

**Comment by zsyzzsoft** [comment]
The DiffAugment operations are supposed to work on all common PyTorch/TensorFlow versions. If it doesn't work properly on some version, just let me know!

**Comment by Johnson-yue** [comment]
@zsyzzsoft  this code work fine on Python 3.5， but not work on Python 3.7， Did you try on Python 3.7??

**Comment by zsyzzsoft** [comment]
I'm using Python 3.7.6. Have you try the *updated* code? Could you share me the complete error message, including which line yields the error?

**Comment by Johnson-yue** [comment]
ok， if I occur same problem， I will report full log here ， and I just close this issue temporarily

**Comment by jjparkcv** [comment]
Has anyone solved this issue? I'm seeing this CuDNN error using Python 3.6.8.

**Comment by jjparkcv** [comment]
> Has anyone solved this issue? I'm seeing this CuDNN error using Python 3.6.8.

Fixed the issue by calling .contiguous() at the end of the rand_translation() function.

**Comment by shengyu-ponyai** [comment]
> > Has anyone solved this issue? I'm seeing this CuDNN error using Python 3.6.8.
> 
> Fixed the issue by calling .contiguous() at the end of the rand_translation() function.

Thanks! Fixed in master.

**Comment by zsyzzsoft** [comment]
Thanks! Fixed in master.
